blog/urls.py
from django.urls import path, include

from blog.views import BaseView, AboutView, PostListView, ContactView, LoginView

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('about/', AboutView.as_view(), name='about'),
    path('projects/', PostListView.as_view(), name='projects'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('login/', LoginView.as_view(), name='login'),
    path('administration/', include('administration.urls'))

]

stonehall/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include


from . import settings

urlpatterns = [
    path('', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                      path('admin/', admin.site.urls),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from markdown import markdown


class Post(models.Model):
    """Post in blog"""
    title = models.CharField(max_length=255, verbose_name='Название поста')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')
    image = models.ImageField(verbose_name='Заглавная фотография')
    image_y_offset = models.IntegerField(verbose_name='Смещение фотографии по оси y', default=0)
    is_on_main_page = models.BooleanField(default=False, verbose_name='Должен ли пост отображаться на главной?')
    short_description = models.CharField(max_length=100, verbose_name='Короткое описание для отображения в некоторых '
                                                                      'местах')
    content = models.TextField(verbose_name='Полное описание работы')
    serial_number = models.IntegerField(verbose_name='Приоритет при выдаче', default=1)

    class Meta:
        ordering = ['serial_number', '-created_at']

    def __str__(self):
        return f'Пост {self.title}'

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

    def get_content_as_markdown(self):
        return mark_safe(markdown(self.content))


class PostImage(models.Model):
    """Images for Post model"""
    image = models.ImageField(verbose_name="Изображение")
    post = models.ForeignKey(Post, verbose_name="Пост, к которому принадлежат изображения", on_delete=models.CASCADE)
    description = models.TextField(verbose_name='Подпись к фотографии', blank=True, null=True)

    def __str__(self):
        return f'Фотография для поста {self.post.title}'

    def get_absolute_url(self):
        return reverse('image_detail', kwargs={'pk': self.pk})

    def get_description_as_markdown(self):
        return mark_safe(markdown(self.description))

blog/forms.py
from django import forms
from django.contrib.auth.models import User

from blog.models import Post, PostImage

FIELDS_IN_POST_FORM = ['title', 'short_description', 'is_on_main_page', 'content', 'image_y_offset', 'serial_number']
FIELDS_IN_IMAGE_FORM = ['post', 'description']


class PostForm(forms.ModelForm):
    """Model post form, if image uploaded"""

    def __init__(self, *args, **kwargs):
        """Add help_text to image_y_offset field"""
        super().__init__(*args, **kwargs)
        self.fields['image_y_offset'].help_text = "Смещение указывается в процентах. " \
                                                  " Имеет смысл только у вертикальных фотографий." \
                                                  " Указывается от 0 до 100, где 100 - самая нижняя точка"

    def clean_image_y_offset(self):
        data = self.cleaned_data['image_y_offset']
        if data < 0 or data > 100:
            raise forms.ValidationError("Значение должно быть от 0 до 100")
        return data

    class Meta:
        model = Post
        fields = FIELDS_IN_POST_FORM[:]
        fields.append('image')


class PostWithoutImageForm(forms.ModelForm):
    """Model post form, if image don`t changed"""

    def clean_image_y_offset(self):
        data = self.cleaned_data['image_y_offset']
        print(data)
        if data < 0 or data > 100:
            raise forms.ValidationError("Значение должно быть от 0 до 100")
        return data

    class Meta:
        model = Post
        fields = FIELDS_IN_POST_FORM[:]


class ImageForm(forms.ModelForm):
    """Model PostImage form, if image uploaded"""

    class Meta:
        model = PostImage
        fields = FIELDS_IN_IMAGE_FORM[:]
        fields.append('image')


class ImageWithoutImageForm(forms.ModelForm):
    """Model PostImage form, if image don`t changed"""

    class Meta:
        model = PostImage
        fields = FIELDS_IN_IMAGE_FORM[:]


class LoginForm(forms.ModelForm):
    """User login form"""
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        """Rename login form fields"""
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['username'].help_text = ''
        self.fields['password'].label = 'Пароль'
        self.fields['password'].help_text = ''

    def clean(self):
        """Username and password validation"""
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с логином {username} не найден в системе.')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError('Пароль введён неверно')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password']

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View, ListView
from django.urls import reverse

from blog.forms import LoginForm
from blog.models import Post
from blog.services import get_posts_for_main_page, save_question_to_db, login_user_to_site
from question.forms import QuestionForm


class BaseView(View):
    """Main page view"""

    def get(self, request, *args, **kwargs):
        main_posts = get_posts_for_main_page()
        form = QuestionForm()
        context = {
            'posts': main_posts,
            'form': form,
        }
        return render(request, 'base.html', context)


class AboutView(View):
    """View with information about firm"""

    def get(self, request, *args, **kwargs):
        form = QuestionForm()
        context = {
            'form': form
        }
        return render(request, 'about.html', context)


class ContactView(View):
    """View with contact information"""

    def get(self, request, *args, **kwargs):
        form = QuestionForm()
        context = {
            'form': form
        }
        return render(request, 'contact.html', context)

    def post(self, request, *args, **kwargs):
        bound_form = QuestionForm(request.POST)
        if bound_form.is_valid():
            save_question_to_db(request, bound_form)
            return HttpResponseRedirect(reverse('contact'))
        context = {
            'form': bound_form,
        }
        return render(request, 'contact.html', context)


class PostListView(ListView):
    """View with all posts"""
    model = Post
    context_object_name = 'posts'
    template_name = 'post_list.html'
    form = QuestionForm()

    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        return context


class LoginView(View):
    """View with user login form"""

    def get(self, request, *args, **kwargs):
        """When login page is called by method GET"""
        form = LoginForm(request.POST or None)
        context = {'form': form}
        return render(request, 'login.html', context)

    def post(self, request, *args, **kwargs):
        """When login page is called by method POST"""
        form = LoginForm(request.POST or None)
        if form.is_valid():
            if login_user_to_site(request, form):
                return HttpResponseRedirect('/')
        return render(request, 'login.html', {'form': form})

blog/templates/include/_card.html
<div class="col-md-4 ftco-animate">
    <div class="work img d-flex align-items-end"
         style="background-image: url({{ post.image.url }});
                 background-position: center {{ post.image_y_offset }}% !important;">

        <a href="{{ post.image.url }}"
           class="icon image-popup d-flex justify-content-center align-items-center">
            <span class="icon-expand"></span>
        </a>
        <button type="button" class="btn btn-primary ml-2" style="z-index: 1" data-toggle="modal"
                data-target="#exampleModal-{{ post.pk }}">
            <span class="icon-info"></span>
        </button>


        <div class="desc w-100 px-4">
            <div class="text w-100 mb-3">
                <span>{{ post.title }}</span>
                <h2><a href="work-single.html">{{ post.short_description }}</a></h2>
            </div>
        </div>
    </div>
</div>

<div class="modal fade"
     id="exampleModal-{{ post.pk }}" tabindex="-1"
     aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered" style="z-index: 1;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Дополнительная информация</h5>
                <button type="button" class="btn-close" data-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row justify-content-center">
                    <img class="img-fluid" src="{{ post.image.url }}" alt="">
                </div>

                <div class="row justify-content-center mt-3">{{ post.get_content_as_markdown }}</div>

                {% for image in post.postimage_set.all %}
                    <div class="row justify-content-center mt-3">
                        <img src="{{ image.image.url }}" class="img-fluid">
                    </div>
                    <div class="row justify-content-center">{{ image.get_description_as_markdown }}</div>
                {% endfor %}
                <br>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    Закрыть
                </button>
            </div>
        </div>
    </div>
</div>

blog/templates/include/_footer.html
<footer class="footer">
    <div class="container-fluid px-lg-5">
        <div class="row">
            <div class="col-md-9 py-5">
                <div class="row">
                    <div class="col-md-4 mb-md-0 mb-4">
                        <h2 class="footer-heading">О нас</h2>
                        <p>Команда «КаменьХолл» работает для того, чтобы Вы могли создать в доме атмосферу уюта и
                            гармонии.</p>
                    </div>
                    <div class="col-md-8">
                        <div class="row justify-content-center">
                            <div class="col-md-12 col-lg-10">
                                <div class="row">
                                    <div class="col-md-6 mb-md-0 mb-4">
                                        <h2 class="footer-heading">Посмотрите</h2>
                                        <ul class="list-unstyled">
                                            <li><a href="{% url 'projects' %}" class="py-1 d-block">Наши проекты</a>
                                            </li>
                                            <li><a href="{% url 'about' %}" class="py-1 d-block">О нас</a></li>
                                            <li><a href="{% url 'contact' %}" class="py-1 d-block">Контакты</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-6 mb-md-0 mb-4">
                                        <h2 class="footer-heading">Свяжитесь с нами</h2>
                                        <ul class="list-unstyled">
                                            <li class="py-1 d-block"><span class="fa fa-phone"></span>+7 923 366 12 51
                                            </li>
                                            <li class="py-1 d-block"><span class="fa fa-paper-plane"></span> <a
                                                    href="mailto:info@yoursite.com">admin@каменьхолл.рф</a></li>
                                            <li class="py-1 d-block"><span class="fa fa-globe"></span><a
                                                    href="{% url 'contact' %}"> Форма обратной связи</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 py-md-5 py-4 aside-stretch-right pl-lg-5">

                {% block feedback %}
                    <h2 class="footer-heading">Задайте вопрос</h2>
                    <form action="{% url 'contact' %}" class="contact-form" method="post">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group">

                                {% if field.errors %}
                                    <div class="alert alert-danger">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}

                                {{ field }}

                            </div>
                        {% endfor %}

                        <div class="form-group">
                            <button type="submit" class="form-control submit px-3">Отправить</button>
                        </div>
                    </form>
                {% endblock %}

            </div>
        </div>
    </div>
</footer>

blog/templates/include/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars"></span> Меню
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}"><a href="{% url 'base' %}"
                                                                                      class="nav-link">Главная</a></li>
                <li class="nav-item {% if request.path == '/about/' %}active{% endif %}"><a href="{% url 'about' %}"
                                                                                            class="nav-link">О нас</a>
                </li>
                <li class="nav-item {% if request.path == '/projects/' %}active{% endif %}"><a
                        href="{% url 'projects' %}" class="nav-link">Проекты</a>
                </li>
                <li class="nav-item {% if request.path == '/contact/' %}active{% endif %}"><a
                        href="{% url 'contact' %}" class="nav-link">Контакты</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if '/administration/' in request.path %}active{% endif %}"><a
                            href="{% url 'administration_base' %}" class="nav-link">Администрирование</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

blog/templates/include/_pagination.html
{% if page_obj.has_other_pages %}
    <div class="demo">
        <nav class="pagination-outer" aria-label="Page navigation">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                            <i class="fa fa-angle-left" aria-hidden="true"></i>
                        </a>
                    </li>
                {% endif %}

                {% for p in page_obj.paginator.page_range %}
                    {% if page_obj.number == p %}
                        <li class="page-item active"><a class="page-link" href="#">{{ p }}</a></li>
                    {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                        <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endif %}

blog/templates/include/_yandex_metrica.html
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(74328490, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/74328490" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->L